// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf-6zUtowDnPI3FZbFEoT5HVJIzduKC00',
    appId: '1:262377789158:web:09d796b7dd518714b98d27',
    messagingSenderId: '262377789158',
    projectId: 'morfo-esp32-test-f581b',
    authDomain: 'morfo-esp32-test-f581b.firebaseapp.com',
    databaseURL: 'https://morfo-esp32-test-f581b-default-rtdb.firebaseio.com',
    storageBucket: 'morfo-esp32-test-f581b.appspot.com',
    measurementId: 'G-T7KDRVSHHE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVOQ2OIg6hapSR1DQWhOtnyqrALgdB50A',
    appId: '1:262377789158:ios:0af219f3f192804ab98d27',
    messagingSenderId: '262377789158',
    projectId: 'morfo-esp32-test-f581b',
    databaseURL: 'https://morfo-esp32-test-f581b-default-rtdb.firebaseio.com',
    storageBucket: 'morfo-esp32-test-f581b.appspot.com',
    iosBundleId: 'com.example.morflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVOQ2OIg6hapSR1DQWhOtnyqrALgdB50A',
    appId: '1:262377789158:ios:0af219f3f192804ab98d27',
    messagingSenderId: '262377789158',
    projectId: 'morfo-esp32-test-f581b',
    databaseURL: 'https://morfo-esp32-test-f581b-default-rtdb.firebaseio.com',
    storageBucket: 'morfo-esp32-test-f581b.appspot.com',
    iosBundleId: 'com.example.morflutter',
  );
}
