name: morflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-169.0.dev <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_database: ^11.0.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Lausane400
      fonts:
        - asset: lib/design/fonts/TWKLausanne-400.otf
    - family: Lausane650
      fonts:
        - asset: lib/design/fonts/TWKLausanne-650.otf


  assets:
    - lib/design/logos/rectangular_vino_violette-removebg-preview-2.png
    - lib/design/logos/cuadrado_blanco_trippypurple-removebg-preview.png
    - lib/design/logos/principal_morado_negro-removebg-preview.png
    - lib/design/logos/rectangular_vino_trippypurplep.png

    
