name: morflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-169.0.dev <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_database: ^11.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
